In [18]:
# Import all modules needed
import sys
import pandas as pd
import matplotlib
import numpy as np
import scipy as sp
import IPython
import sklearn

In [19]:
# print versions being used
print("Python version: {}".format(sys.version))
print("pandas version: {}".format(pd.__version__))
print("matplotlib version: {}".format(matplotlib.__version__))
print("NumPy version: {}".format(np.__version__))
print("SciPy version: {}".format(sp.__version__))
print("IPython version: {}".format(IPython.__version__))
print("scikit-learn version: {}".format(sklearn.__version__))

Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
pandas version: 2.2.2
matplotlib version: 3.8.4
NumPy version: 1.26.4
SciPy version: 1.13.1
IPython version: 8.25.0
scikit-learn version: 1.5.1


In [20]:
# load iris dataset from scikit_learn
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [21]:
# the iris object loaded is a Bunch object, similar to a dictionary containing Key:Value pairs
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [22]:
# A string that contains detailed text description of the dataset 
# ['what you want to see'][:slicing to the number of characters]
# the elipsis ... means that there is more to read after
print(iris_dataset['DESCR'][:440]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica


...


In [23]:
# A NumPy 'array' that contains the names of the target classes
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [24]:
# '{}' is the place holder for the .format() method where (datset[list])
print("Feature names: \n{}".format(iris_dataset['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [25]:
# print lines of the dataset .format(dataset['list'][slice:lines])
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Training and Testing
- When assessing a model's performance, the labeled data (input data that has been annotated with the correct output or target value (each data point is paired with a label or category that it belongs to))

**The data is broken into two parts, one to build the model**
- Training Data (Training Set) is usually about 70% - 80%

**The rest is used to assess how well the model works**
- Test Data (Test Set) (Hold-out Set) is usually about 20% - 30%